### ISSUE TITLE
MassDestroy do not save log

### ISSUE THREAD

**Issue by kinzinho666** [yajra/laravel-auditable#11]
Laravel 7

Actual Behaviour
Do not save log when a use DataTables MassDestroy, if i remove just only one, log save OK.

Model friends.php

```
namespace App;

use App\Traits\Auditable;
use Yajra\Auditable\AuditableWithDeletesTrait;`

class ProcedureType extends Model
{
    use SoftDeletes, MultiTenantModelTrait, Auditable, AuditableWithDeletesTrait;

   protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];
 protected $fillable = [
        'title',
        'created_at',
        'updated_at',
        'deleted_at',
        'created_by_id',
    ];
```
Controller app\http\admin\FriendsController.php

```
public function destroy(Friends $friends)
    {
        abort_if(Gate::denies('friends_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $friends->delete();

        return back();

    }
public function massDestroy(MassDestroyFriendsRequest $request)
    {
        Friends::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);

    }

```

Steps to Reproduce
composer require yajra/laravel-auditable

composer update

open my friends page

select 2 or more on checkbox and click em Mass Destroy (datatables)

**Comment by yajra** [comment]
Can't recall but does softDeletes work with mass delete? If yes, then this can be considered as an enhancement. Thanks!

**Comment by ognjen-petrovic** [comment]
Reason could be, from Laravel's documentation https://laravel.com/docs/8.x/eloquent#events:

>  When issuing a mass update or delete via Eloquent, the saved, updated, deleting, and deleted model events will not be fired for the affected models. This is because the models are never actually retrieved when issuing a mass update or delete.

Doing something like this will fire events:
`Friends::find($ids)->each(function($friend){$friend->delete();});`

**Comment by yajra** [comment]
@ognjen-petrovic thanks for that info. I think that is enough to solve this issue.
