### ISSUE TITLE
Soft Delete

### ISSUE THREAD

**Issue by gpibarra** [yajra/laravel-auditable#7]
To detect model use "soft delete" 

in src/AuditableTraitObserver.php:
```php
if ($model->getConnection()->getSchemaBuilder()->hasColumn($model->getTable(), $deletedBy)) {
```

It would be better to use (faster without calling the db)

```php
if (method_exists($model, 'getDeletedAtColumn')) {
```
That method will exist if the "soft delete" trait was used

https://laravel.com/api/5.8/Illuminate/Database/Eloquent/SoftDeletes.html#method_getDeletedAtColumn

**Comment by yajra** [comment]
@gpibarra great suggestion. However, I think it was done that way to provide backward compatibility. V2 of the package does not have `deleted_by` column and the method above will always assume that we have it thus making our deleting observer to fail.

**Comment by gpibarra** [comment]
well, as there are 2 ways to do the migration (with and without deletes), then there are 2 traits, the first one compatible with v2 and the second one "with deletes" that extends from the previous one.

**Comment by yajra** [comment]
2 traits might be a good to deal with this along with 2 observers maybe. Tagging for enhancement, will try to implement when I got the chance. If you can, please do not hesitate to submit a PR. Thanks!
